# Generated by Django 5.0.1 on 2024-02-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
