# Generated by Django 5.0.1 on 2024-02-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherStudentRelationship',
        ),
    ]
