# Generated by Django 5.0.1 on 2024-02-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0007_teacher_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(blank=True, to='teaching.student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teaching.teacher'),
            preserve_default=False,
        ),
    ]
