# Generated by Django 5.0.1 on 2024-02-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0012_delete_requestteaching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='title',
            new_name='tittle',
        ),
    ]
