# Generated by Django 5.0.1 on 2024-02-08 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0013_rename_title_homework_tittle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='students',
        ),
        migrations.AddField(
            model_name='homework',
            name='students',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='teaching.student'),
            preserve_default=False,
        ),
    ]
