# Generated by Django 5.0.1 on 2024-02-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0016_homework_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
