# Generated by Django 5.0.1 on 2024-02-10 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0018_homework_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
